cflags = " -flto=thin --target=arm-none-eabi -O0 -g"
platform = ARGUMENTS.get('platform', "stm32")
if platform == "stm32":
	cflags  = cflags + " -DCONFIG_CPU_CORTEX_M4 -DSTM32F4xx -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "
env = Environment()
env.Import('*')
dir = Dir("./CMSIS/Include/")
gcc_path = Dir("/usr/lib/gcc/arm-none-eabi/9.2.1/include")
env.Append(CPPPATH = gcc_path)
env.Append(CPPPATH = dir)
env.Append(CCFLAGS = cflags)
objs= env.Object(source = [env.Glob("./*.c")])
Return("objs")


